#!/bin/sh

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
source /etc/init.d/denylist
for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
     if [[ "${deny_list[@]}" =~ "${i/\/etc\/init.d\//}" ]]; then
        echo "$i skip"
        continue
     fi

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
    esac
done
devmem 0xfa23fbd0 32 0xf5f5f5f5
echo 0 > /sys/devices/system/cpu/cpu1/online
echo 0 > /sys/devices/system/cpu/cpu2/online
echo 0 > /sys/devices/system/cpu/cpu3/online
echo 1 > /sys/kernel/debug/regulator/3-0030-BUCK1/enable
