#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

source /etc/init.d/denylist

if [ -f /etc/init.d/rc.emmc_userdata ];then
	/etc/init.d/rc.emmc_userdata
fi

#if [ -f /etc/init.d/rc.extra ];then
#	echo "rc.extra [bg]"
#	/etc/init.d/rc.extra &
#fi

#if [ -f /etc/init.d/rc.sdcardboot ];then
#	/etc/init.d/rc.sdcardboot
#else
#	/etc/init.d/rc.resizefs
#fi

#if [ -f /etc/init.d/rc.npu  ];then
#        /etc/init.d/rc.npu
#fi

if [ -f /etc/init.d/rc.vitron_soft_link  ];then
        /etc/init.d/rc.vitron_soft_link start
fi

if [ -f /etc/init.d/rc.ndk  ];then
        /etc/init.d/rc.ndk start
fi

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
	if [[ "${deny_list[@]}" =~ "${i/\/etc\/init.d\//}" ]]; then
        echo "$i skip"
        continue
    fi
     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

devmem 0xfa23fbd0 32  0
echo schedutil > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
