#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
	echo "Starting watchdog..."
	watchdog
	;;
  stop)
	killall watchdog
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
