#!/bin/sh
#
# setup configfs for adbd, usb mass storage and MTP....
# For kernel v4.4 usb configfs
#
# Load default env variables from profiles
. /etc/profile

UMS_EN=off
ADB_EN=off
MTP_EN=off
NTB_EN=off
ACM_EN=off
UAC1_EN=off
UAC2_EN=off
UVC_EN=off
UVC2_EN=off
RNDIS_EN=off
HID_EN=off

USB_ATTRIBUTE=0x409
USB_GROUP=vicoretek
USB_SKELETON=b.1

CONFIGFS_DIR=/sys/kernel/config
USB_CONFIGFS_DIR=${CONFIGFS_DIR}/usb_gadget/${USB_GROUP}
USB_STRINGS_DIR=${USB_CONFIGFS_DIR}/strings/${USB_ATTRIBUTE}
USB_FUNCTIONS_DIR=${USB_CONFIGFS_DIR}/functions
USB_CONFIGS_DIR=${USB_CONFIGFS_DIR}/configs/${USB_SKELETON}

GADGET_DEVICE=usb3


# For VBUS_ALWAYS_ON usb otg is not support ums
# Since the block to ums is always occupated by USB due to no disconneted state
UMS_BLOCK=/opt/ums_file.img
UMS_BLOCK_SIZE=128	#unit M
UMS_BLOCK_TYPE=fat
UMS_BLOCK_AUTO_MOUNT=off
UMS_RO=0
#use sdcard boot partition as default.
UMS_LUN_DEFAULT_FILE=/dev/mmcblk1p1
#lun file should be block device such as emmc/sdcard blk, or ums_file.img
UMS_LUN_FILE=""

UVC_DIR=${USB_FUNCTIONS_DIR}/uvc.gs6/
UVC_STREAMING_DIR=${UVC_DIR}/streaming/
UVC_CONTROL_DIR=${UVC_DIR}/control/
UVC_U_DIR=${UVC_STREAMING_DIR}/uncompressed/u/
UVC_M_DIR=${UVC_STREAMING_DIR}/mjpeg/m/
#UVC_F_DIR=${UVC_STREAMING_DIR}/framebased/f/
UVC2_DIR=${USB_FUNCTIONS_DIR}/uvc.gs7/
UVC2_STREAMING_DIR=${UVC2_DIR}/streaming/
UVC2_CONTROL_DIR=${UVC2_DIR}/control/
UVC2_U_DIR=${UVC2_STREAMING_DIR}/uncompressed/u/
UVC2_M_DIR=${UVC2_STREAMING_DIR}/mjpeg/m/

ALL_UVC_FPS_INFO=()

test_write()
{
	test -e $2 && echo $1 > $2
}

function_init()
{
	mkdir ${USB_FUNCTIONS_DIR}/uac1.gs0
	test_write 1 ${USB_FUNCTIONS_DIR}/uac1.gs0/c_feature_unit
	test_write 1 ${USB_FUNCTIONS_DIR}/uac1.gs0/p_feature_unit
	mkdir ${USB_FUNCTIONS_DIR}/uac2.gs0
	test_write 1 ${USB_FUNCTIONS_DIR}/uac2.gs0/c_feature_unit
	test_write 1 ${USB_FUNCTIONS_DIR}/uac2.gs0/p_feature_unit
	mkdir ${USB_FUNCTIONS_DIR}/ffs.adb
	mkdir ${USB_FUNCTIONS_DIR}/ffs.ntb
	#mkdir ${USB_FUNCTIONS_DIR}/mtp.gs0
	mkdir ${USB_FUNCTIONS_DIR}/rndis.gs0
	#write /config/usb_gadget/g1/functions/rndis.gs0/wceis 1
	mkdir ${USB_FUNCTIONS_DIR}/acm.gs6
	mkdir ${USB_FUNCTIONS_DIR}/mass_storage.0
	mkdir ${USB_FUNCTIONS_DIR}/uvc.gs6
	mkdir ${USB_FUNCTIONS_DIR}/uvc.gs7
}

configfs_init()
{
	echo "Debug: configfs_init" >/dev/null 2>&1
	mkdir /dev/usb-ffs

	mount -t configfs none ${CONFIGFS_DIR}
	mkdir ${USB_CONFIGFS_DIR} -m 0770
	echo 0x37a4 > ${USB_CONFIGFS_DIR}/idVendor
	echo 0x0310 > ${USB_CONFIGFS_DIR}/bcdDevice
	echo 0x0200 > ${USB_CONFIGFS_DIR}/bcdUSB
	mkdir ${USB_STRINGS_DIR}   -m 0770
	MMC_SERIAL=$(cat /sys/class/mmc_host/mmc0/mmc0:0001/serial)
        SERIAL=${MMC_SERIAL:2}
	if [ -z $SERIAL ];then
		SERIAL=0123456789ABCDEF
	fi
	echo $SERIAL > ${USB_STRINGS_DIR}/serialnumber
	echo "Vicore"  > ${USB_STRINGS_DIR}/manufacturer
	echo "Vicore device"  > ${USB_STRINGS_DIR}/product

	function_init

	mkdir ${USB_CONFIGS_DIR}  -m 0770
	mkdir ${USB_CONFIGS_DIR}/strings/${USB_ATTRIBUTE}  -m 0770

	echo 0x1 > ${USB_CONFIGFS_DIR}/os_desc/b_vendor_code
	echo "MSFT100" > ${USB_CONFIGFS_DIR}/os_desc/qw_sign
	echo 500 > ${USB_CONFIGS_DIR}/MaxPower
	ln -s ${USB_CONFIGS_DIR} ${USB_CONFIGFS_DIR}/os_desc/${USB_SKELETON}
}

make_config_string()
{
	tmp=$CONFIG_STRING
	if [ -n "$CONFIG_STRING" ]; then
		CONFIG_STRING=${tmp}_${1}
	else
		CONFIG_STRING=$1
	fi
}

parse_parameter()
{
	# find name and var
	NAME=`echo $1 | awk -F "=" '{print $1}'`
	VAR=`echo $1 | awk -F "=" '{print $2}'`

	case "$NAME" in
		ums_block)
			UMS_BLOCK=${VAR}
			;;
		ums_block_size)
			if [ ! "$VAR" -gt 0 ] 2>/dev/null ;then
				echo "$VAR is not a number"
				exit 1
			fi
			UMS_BLOCK_SIZE=${VAR}
			;;
		ums_block_type)
			UMS_BLOCK_TYPE=${VAR}
			;;
		ums_block_auto_mount)
			UMS_BLOCK_AUTO_MOUNT=${VAR}
			;;
		ums_lun_file)
			UMS_LUN_FILE=${VAR}
			;;
		ums_ro)
			if [ "$VAR" != "off" ]; then
				echo "Set UMS read-only"
				UMS_RO=1
			fi
				UMS_RO=0
			;;
		gadget_device)
			GADGET_DEVICE=${VAR}
			;;
	esac
}

parameter_init()
{
	while read line
	do
		case "$line" in
			usb_mtp_en)
				MTP_EN=on
				make_config_string mtp
				;;
			usb_adb_en)
				ADB_EN=on
				make_config_string adb
				;;
			usb_ums_en)
				UMS_EN=on
				make_config_string ums
				;;
			usb_ntb_en)
				NTB_EN=on
				make_config_string ntb
				;;
			usb_acm_en)
				ACM_EN=on
				make_config_string acm
				;;
			usb_uac1_en)
				UAC1_EN=on
				make_config_string uac1
				;;
			usb_uac2_en)
				UAC2_EN=on
				make_config_string uac2
				;;
			usb_uvc_en)
				UVC_EN=on
				echo "UVC_EN=on"
				make_config_string uvc
				;;
			usb_uvc2_en)
				UVC2_EN=on
				echo "UVC2_EN=on"
				make_config_string uvc2
				;;
			usb_uvc_bulk_mode_en)
				UVC_BULK_MODE_EN=on
				echo "UVC_BULK_MODE_EN=on"
				;;
			usb_rndis_en)
				RNDIS_EN=on
				make_config_string rndis
				;;
			usb_hid_en)
				HID_EN=on
				make_config_string hid
				;;
			*)
				parse_parameter ${line}
				;;
		esac
	done < $USB_CONFIG_FILE

	case "$CONFIG_STRING" in
		ums)
			PID=0x0001
			;;
		adb)
			PID=0x4E21
			;;
		rndis)
			PID=0x4e13
			;;
		ums_adb | adb_ums)
			PID=0x0100
			;;
		rndis_adb | adb_rndis)
			PID=0x4E24
			;;
		*)
			PID=0x4E24
	esac
}

use_os_desc()
{
	if [ $MTP_EN = on ];then
		echo "MTP" > ${USB_FUNCTIONS_DIR}/mtp.gs0/os_desc/interface.MTP/compatible_id
		echo 1 > ${USB_CONFIGFS_DIR}/os_desc/use
	fi
}

pre_run_binary()
{
	if [ $ADB_EN = on ];then
		mkdir /dev/usb-ffs/adb -m 0770
		mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
		start-stop-daemon --start --quiet --background --exec /usr/bin/adbd
	fi

	if [ $NTB_EN = on ];then
		mkdir /dev/usb-ffs/ntb -m 0770
		mount -o uid=2000,gid=2000 -t functionfs ntb /dev/usb-ffs/ntb
		# Not start app here
	fi

	# Add uvc app here with start-stop-daemon
}

configure_uvc_resolution_yuyv()
{
	W=$1
	H=$2
	DIR=$3/${W}p/
	#echo  0 > ${UVC_U_DIR}/bDefaultFrameIndex
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 333333 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*30*16)) > ${DIR}/dwMinBitRate
	echo $((W*H*30*16)) > ${DIR}/dwMaxBitRate
	echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	cat <<EOF  > ${DIR}/dwFrameInterval
333333
666666
1000000
2000000
EOF
}

configure_uvc_resolution_yuyv_3840()
{
	W=$1
	H=$2
	DIR=$3/${W}p/
	#echo  0 > ${UVC_U_DIR}/bDefaultFrameIndex
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 333333 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*30*16)) > ${DIR}/dwMinBitRate
	echo $((W*H*30*16)) > ${DIR}/dwMaxBitRate
	echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	cat <<EOF  > ${DIR}/dwFrameInterval
100000
333333
EOF
}

configure_uvc_resolution_yuyv_3840_H()
{
	W=$1
	H=$2
	DIR=$3/${H}p/
	#echo  0 > ${UVC_U_DIR}/bDefaultFrameIndex
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 100000 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*30*16)) > ${DIR}/dwMinBitRate
	echo $((W*H*30*16)) > ${DIR}/dwMaxBitRate
	echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	cat <<EOF  > ${DIR}/dwFrameInterval
100000
EOF
}

configure_uvc_resolution_mjpeg()
{
	W=$1
	H=$2
	DIR=$3/${H}p/
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 333333 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*20)) > ${DIR}/dwMinBitRate
	echo $((W*H*20)) > ${DIR}/dwMaxBitRate
	echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	cat <<EOF  > ${DIR}/dwFrameInterval
333333
666666
1000000
2000000
EOF
}

configure_uvc_resolution_mjpeg_3840()
{
	W=$1
	H=$2
	DIR=$3/${W}p/
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 333333 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*20)) > ${DIR}/dwMinBitRate
	echo $((W*H*20)) > ${DIR}/dwMaxBitRate
	echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	cat <<EOF  > ${DIR}/dwFrameInterval
333333
666666
1000000
2000000
EOF
}

configure_uvc_resolution_h264()
{
	W=$1
	H=$2
	DIR=$3/${H}p/
	mkdir ${DIR}
	echo $W > ${DIR}/wWidth
	echo $H > ${DIR}/wHeight
	echo 333333 > ${DIR}/dwDefaultFrameInterval
	echo $((W*H*10)) > ${DIR}/dwMinBitRate
	echo $((W*H*10)) > ${DIR}/dwMaxBitRate
	#echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
	#echo -e "333333\n666666\n1000000\n2000000" > ${DIR}/dwFrameInterval
	cat <<EOF  > ${DIR}/dwFrameInterval
333333
666666
1000000
2000000
EOF
}

syslink_function()
{
	echo "$1"
	ln -s ${USB_FUNCTIONS_DIR}/$1 ${USB_CONFIGS_DIR}/f${USB_FUNCTIONS_CNT}
	let USB_FUNCTIONS_CNT=USB_FUNCTIONS_CNT+1
}

function setup_hid_imu()
{
    hid_imu_path="hid.imu"
    mkdir ${USB_FUNCTIONS_DIR}/${hid_imu_path}
    for file in $(ls /etc/sunplus/hid_desc/*)
    do
	    echo $file
	    break
    done
    HID_PROTOCOL=`ls $file | awk -F '_' '{print $4}'`
    HID_REPORT_LEN=`ls $file | awk -F '_' '{print $5}' |  awk -F '.' '{print $1}'`
    echo "hid protocol:"$HID_PROTOCOL
    echo "report len:"$HID_REPORT_LEN
    echo $HID_PROTOCOL > ${USB_FUNCTIONS_DIR}/${hid_imu_path}/protocol
    echo 0 > ${USB_FUNCTIONS_DIR}/${hid_imu_path}/subclass
    echo $HID_REPORT_LEN > ${USB_FUNCTIONS_DIR}/${hid_imu_path}/report_length
    cat $file > ${USB_FUNCTIONS_DIR}/${hid_imu_path}/report_desc

    ln -s ${USB_FUNCTIONS_DIR}/${hid_imu_path} ${USB_CONFIGS_DIR}/f${USB_FUNCTIONS_CNT}
    let USB_FUNCTIONS_CNT=USB_FUNCTIONS_CNT+1
}

configure_uvc_resolution_fps_yuyv()
{
    W=$1
    H=$2
    FPS=$3
    F=$((10000000 / FPS))

    DIR=$4${W}p/
    if [ $5 -eq 1 ];then
        DIR=$4${H}p/
    fi
    echo "DIR: $DIR"

    mkdir -p ${DIR}
    echo $W > ${DIR}/wWidth
    echo $H > ${DIR}/wHeight
    echo $F > ${DIR}/dwDefaultFrameInterval

    echo $((W*H*30*16)) > ${DIR}/dwMinBitRate
    echo $((W*H*30*16)) > ${DIR}/dwMaxBitRate
    echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize

    cat <<EOF  > ${DIR}/dwFrameInterval
$(for item in "${ALL_UVC_FPS_INFO[@]}"; do echo "$item"; done)
EOF
}

configure_uvc_resolution_yuyv_W()
{
    W=$1
    H=$2
    DIR=$3/${W}p/
    #echo  0 > ${UVC_U_DIR}/bDefaultFrameIndex
    mkdir ${DIR}
    echo $W > ${DIR}/wWidth
    echo $H > ${DIR}/wHeight
    echo 333333 > ${DIR}/dwDefaultFrameInterval
    echo $((W*H*30*16)) > ${DIR}/dwMinBitRate
    echo $((W*H*30*16)) > ${DIR}/dwMaxBitRate
    echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize
    cat <<EOF  > ${DIR}/dwFrameInterval
EOF
}


configure_uvc_resolution_fps_mjpeg()
{
    W=$1
    H=$2
    FPS=$3
    F=$((10000000 / FPS))

    DIR=$4${W}p/
    if [ $5 -eq 1 ];then
        DIR=$4${H}p/
    fi
    echo "DIR: $DIR"

    mkdir -p ${DIR}
    echo $W > ${DIR}/wWidth
    echo $H > ${DIR}/wHeight
    echo $F > ${DIR}/dwDefaultFrameInterval

    echo $((W*H*20)) > ${DIR}/dwMinBitRate
    echo $((W*H*20)) > ${DIR}/dwMaxBitRate
    echo $((W*H*2)) > ${DIR}/dwMaxVideoFrameBufferSize

    cat <<EOF  > ${DIR}/dwFrameInterval
$(for item in "${ALL_UVC_FPS_INFO[@]}"; do echo "$item"; done)
EOF
}

function get_all_fps_info()
{
    # default fps info
    local all_fps_info=(100000 333333 1000000)
    uvc_config_file=$1
    if [ ! -f "$uvc_config_file" ]; then
        echo "No $uvc_config_file found"
        return 0
    fi

    all_fps=(`cat $uvc_config_file | grep -v "^#" | awk -F',' '{print $3}'`)
    for fps in "${all_fps[@]}"; do
        if [[ ! "$fps" =~ ^[0-9]+$ || $fps -lt 1 || $fps -gt 400 ]]; then
            continue
        fi

        fps_val=$((10000000 / fps))
        all_fps_info+=($fps_val)
    done

    all_fps_info=($(for item in "${all_fps_info[@]}"; do echo "$item"; done | sort -n | uniq))
    echo "${all_fps_info[@]}"
}

function deal_uvc_config_file()
{
    uvc_config_file=$1
    if [ ! -f "$uvc_config_file" ]; then
        echo "No $uvc_config_file found"
        return 0
    fi

    ALL_UVC_FPS_INFO=($(get_all_fps_info $uvc_config_file))
    echo "all uvc fps info: ${ALL_UVC_FPS_INFO[@]}"

    uvc_yuyv_dir=${UVC_U_DIR}
    uvc_mjpeg_dir=${UVC_M_DIR}
    uvc_streaming_dir=${UVC_STREAMING_DIR}
    uvc_index=$2
    if [ X"$uvc_index" = X"2" ]; then
        uvc_yuyv_dir=${UVC2_U_DIR}
        uvc_mjpeg_dir=${UVC2_M_DIR}
        uvc_streaming_dir=${UVC2_STREAMING_DIR}
    fi

    mkdir -p ${uvc_yuyv_dir}
    mkdir -p ${uvc_mjpeg_dir}

    is_had_yuyv=0
    is_had_mjpeg=0
    declare -A resolution_format_count
    camera_00=$(media-ctl -p -d /dev/media0 | grep -m 1 m00_ | awk -F"\"" '{print $2}' | awk -F"_" '{print $3}' | awk '{print $1}')
    camera_01=$(media-ctl -p -d /dev/media0 | grep -m 1 m01_ | awk -F"\"" '{print $2}' | awk -F"_" '{print $3}' | awk '{print $1}')
    camera_02=$(media-ctl -p -d /dev/media0 | grep -m 1 m02_ | awk -F"\"" '{print $2}' | awk -F"_" '{print $3}' | awk '{print $1}')
    camera_03=$(media-ctl -p -d /dev/media0 | grep -m 1 m03_ | awk -F"\"" '{print $2}' | awk -F"_" '{print $3}' | awk '{print $1}')

    ALL_RESOLUTIONS=($(lua ${uvc_config_file} ${camera_00}${camera_00}${camera_02}${camera_03}))

    for line in "${ALL_RESOLUTIONS[@]}"; do
        trimmed_line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        # Skip blank and comment lines
        if [[ -z "$trimmed_line" || $trimmed_line == \#* ]]; then
            continue
        fi

        read -r width height fps format <<< $(echo "$trimmed_line" | awk -F',' '{print $1, $2, $3, $4}')
        echo "read width: $width, height: $height, fps: $fps, format: $format"

        width=$(echo "$width" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        height=$(echo "$height" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        fps=$(echo "$fps" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        format=$(echo "$format" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

        if [[ -z "$width" || -z "$height" || -z "$fps" || -z "$format" ]]; then
            echo "Invalid line: $trimmed_line"
            continue
        fi

        if [[ ! "$width" =~ ^[0-9]+$ || $width -lt 1 || $width -gt 65535 ]]; then
            echo "Invalid width: $width"
            continue
        fi

        if [[ ! "$height" =~ ^[0-9]+$ || $height -lt 1 || $height -gt 65535 ]]; then
            echo "Invalid height: $height"
            continue
        fi

        if [[ ! "$fps" =~ ^[0-9]+$ || $fps -lt 1 || $fps -gt 400 ]]; then
            echo "Invalid fps: $fps"
            continue
        fi

        format=$(echo "$format" | tr '[:upper:]' '[:lower:]')
        format=(${format//|/ })

        for one_format in "${format[@]}"; do
            one_format=$(echo "$one_format" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            resolution_format="${width}_${one_format}"
            count=${resolution_format_count[$resolution_format]}

            is_use_height=0
            if [ -z "$count" ]; then
                resolution_format_count[$resolution_format]=1
            else
                resolution_format="${height}_${one_format}"
                count=${resolution_format_count[$resolution_format]}

                if [ -z "$count" ]; then
                    resolution_format_count[$resolution_format]=1
                else
                    echo "Too many format for resolution: $width x $height @ $fps $one_format"
                    continue
                fi
                is_use_height=1
            fi

            echo "Deal with resolution: $width x $height @ $fps $one_format"
            case "$one_format" in
                "yuyv")
                    configure_uvc_resolution_fps_yuyv $width $height $fps $uvc_yuyv_dir $is_use_height
                    is_had_yuyv=1
                    ;;
                "mjpeg")
                    configure_uvc_resolution_fps_mjpeg $width $height $fps $uvc_mjpeg_dir $is_use_height
                    is_had_mjpeg=1
                    ;;
                *)  # default
                    echo "Invalid format: $one_format"
                    ;;
            esac
        done
    done

    # Only create soft link if had config
    if [ $is_had_yuyv -eq 1 ]; then
        ln -s ${uvc_yuyv_dir} ${uvc_streaming_dir}/header/h/u
    fi

    if [ $is_had_mjpeg -eq 1 ]; then
        ln -s ${uvc_mjpeg_dir} ${uvc_streaming_dir}/header/h/m
    fi
}

bind_functions()
{
    USB_FUNCTIONS_CNT=1
    test $UAC1_EN = on && syslink_function uac1.gs0
    test $UAC2_EN = on && syslink_function uac2.gs0

    if [ $UVC_EN = on ];then
        mkdir ${UVC_CONTROL_DIR}/header/h
        ln -s ${UVC_CONTROL_DIR}/header/h ${UVC_CONTROL_DIR}/class/fs/h
        ln -s ${UVC_CONTROL_DIR}/header/h ${UVC_CONTROL_DIR}/class/ss/h

        mkdir ${UVC_STREAMING_DIR}/header/h
        UVC_NORMAL_CONFIG_FILE=/etc/vicore/vision/conf/uvc_pipeline_router.lua
        if [ -f "$UVC_NORMAL_CONFIG_FILE" ]; then
            deal_uvc_config_file $UVC_NORMAL_CONFIG_FILE
        else
            ##YUYV support config
            mkdir ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv 640 480 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv_W 1280 480 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv 1280 720 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv_W 2560 720 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv 1280 960 ${UVC_U_DIR}
	    configure_uvc_resolution_yuyv 2560 1440 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv_W  1920 1080 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv_3840  3840  1080 ${UVC_U_DIR}
	    # configure_uvc_resolution_yuyv_3840_H  3840  1080 ${UVC_U_DIR}

	    configure_uvc_resolution_yuyv 1280 480 ${UVC_U_DIR}
	    #configure_uvc_resolution_yuyv 3200 1200 ${UVC_U_DIR}
	    configure_uvc_resolution_yuyv 3200 2400 ${UVC_U_DIR}

	    configure_uvc_resolution_yuyv 2560 960 ${UVC_U_DIR}
	    configure_uvc_resolution_yuyv_W  3840 960 ${UVC_U_DIR}

	    ##mjpeg support config
	    # mkdir ${UVC_M_DIR}
	    # configure_uvc_resolution_mjpeg 640 480 ${UVC_M_DIR}
	    # configure_uvc_resolution_mjpeg 1280 720 ${UVC_M_DIR}
	    # configure_uvc_resolution_mjpeg 1920 1080 ${UVC_M_DIR}
	    # configure_uvc_resolution_mjpeg_3840 3840 1080 ${UVC_M_DIR}
	    #configure_uvc_resolution_mjpeg 2560 1440
	    #configure_uvc_resolution_mjpeg 2592 1944

	    ## h.264 support config
	    #mkdir ${UVC_F_DIR}
	    #configure_uvc_resolution_h264 640 480
	    #configure_uvc_resolution_h264 1280 720
	    #configure_uvc_resolution_h264 1920 1080

            mkdir ${UVC_STREAMING_DIR}/header/h
            ln -s ${UVC_U_DIR} ${UVC_STREAMING_DIR}/header/h/u
            ln -s ${UVC_M_DIR} ${UVC_STREAMING_DIR}/header/h/m
        fi

        ln -s ${UVC_STREAMING_DIR}/header/h ${UVC_STREAMING_DIR}/class/fs/h
        ln -s ${UVC_STREAMING_DIR}/header/h ${UVC_STREAMING_DIR}/class/hs/h
        ln -s ${UVC_STREAMING_DIR}/header/h ${UVC_STREAMING_DIR}/class/ss/h

        if [ $UVC2_EN = on ];then
            echo 2048 > ${UVC_DIR}/streaming_maxpacket
        else
            echo 3072 > ${UVC_DIR}/streaming_maxpacket
        fi

        echo 15 > ${UVC_DIR}/streaming_maxburst
        echo 0 > ${UVC_DIR}/streaming_interval

        if [[ $UVC_BULK_MODE_EN = on ]];then
            echo 1 > ${UVC_DIR}/streaming_bulk
        fi

        syslink_function uvc.gs6
    fi

    if [ $UVC2_EN = on ];then
        mkdir ${UVC2_CONTROL_DIR}/header/h
        ln -s ${UVC2_CONTROL_DIR}/header/h ${UVC2_CONTROL_DIR}/class/fs/h
        ln -s ${UVC2_CONTROL_DIR}/header/h ${UVC2_CONTROL_DIR}/class/ss/h

        mkdir ${UVC2_STREAMING_DIR}/header/h
        UVC_DEPTHL_CONFIG_FILE=/etc/vicore/uvc/depth.conf
        if [ -f "$UVC_DEPTHL_CONFIG_FILE" ]; then
            deal_uvc_config_file $UVC_DEPTHL_CONFIG_FILE 2
        else
            ##YUYV support config
            mkdir ${UVC2_U_DIR}
            configure_uvc_resolution_yuyv 640 480 ${UVC2_U_DIR}
            configure_uvc_resolution_yuyv 1280 720 ${UVC2_U_DIR}
            configure_uvc_resolution_yuyv 1920 1080 ${UVC2_U_DIR}

            ##mjpeg support config
            mkdir ${UVC2_M_DIR}
            configure_uvc_resolution_mjpeg 640 480 ${UVC2_M_DIR}
            configure_uvc_resolution_mjpeg 1280 720 ${UVC2_M_DIR}
            configure_uvc_resolution_mjpeg 1920 1080 ${UVC2_M_DIR}

            mkdir ${UVC2_STREAMING_DIR}/header/h
            ln -s ${UVC2_U_DIR} ${UVC2_STREAMING_DIR}/header/h/u
            ln -s ${UVC2_M_DIR} ${UVC2_STREAMING_DIR}/header/h/m
        fi

        ln -s ${UVC2_STREAMING_DIR}/header/h ${UVC2_STREAMING_DIR}/class/fs/h
        ln -s ${UVC2_STREAMING_DIR}/header/h ${UVC2_STREAMING_DIR}/class/hs/h
        ln -s ${UVC2_STREAMING_DIR}/header/h ${UVC2_STREAMING_DIR}/class/ss/h

        echo  0 > ${UVC2_DIR}/streaming_interval
        echo  6 > ${UVC2_DIR}/streaming_maxburst
        echo 2048 > ${UVC2_DIR}/streaming_maxpacket

        if [[ $UVC_BULK_MODE_EN = on ]];then
            echo 1 > ${UVC2_DIR}/streaming_bulk
        fi

        syslink_function uvc.gs7
    fi

    test $MTP_EN = on && syslink_function mtp.gs0
    test $NTB_EN = on && syslink_function ffs.ntb
    test $ADB_EN = on && syslink_function ffs.adb
    test $ACM_EN = on && syslink_function acm.gs6
    test $RNDIS_EN = on && syslink_function rndis.gs0

    if [ $HID_EN = on ]; then
        setup_hid_imu
    fi

    if [ $UMS_EN = on ];then
        echo ${UMS_RO} > ${USB_FUNCTIONS_DIR}/mass_storage.0/lun.0/ro
        if [ "$UMS_BLOCK_SIZE" != "0" -a ! -e ${UMS_BLOCK} ]; then
            dd if=/dev/zero of=${UMS_BLOCK} bs=1M count=${UMS_BLOCK_SIZE}
            mkfs.${UMS_BLOCK_TYPE} ${UMS_BLOCK}
            test $? && echo "Warning: failed to mkfs.${UMS_BLOCK_TYPE} ${UMS_BLOCK}"
        fi
        mkdir /mnt/ums -p
        if [[ $UMS_BLOCK_AUTO_MOUNT = on ]];then
            mount ${UMS_BLOCK} /mnt/ums
        else
            if [[  -n "$UMS_LUN_FILE"  &&  -e "$UMS_LUN_FILE"  ]]; then
                echo ${UMS_LUN_FILE} > ${USB_FUNCTIONS_DIR}/mass_storage.0/lun.0/file
                echo "${UMS_LUN_FILE} used as lun file"
            else
                echo ${UMS_LUN_DEFAULT_FILE} > ${USB_FUNCTIONS_DIR}/mass_storage.0/lun.0/file
                echo "${UMS_LUN_DEFAULT_FILE} used as lun file"
            fi
        fi
        syslink_function mass_storage.0
    fi

    echo ${CONFIG_STRING} > ${USB_CONFIGS_DIR}/strings/${USB_ATTRIBUTE}/configuration
}

run_binary()
{
	if [ $MTP_EN = on ];then
		start-stop-daemon --start --quiet --background --exec /usr/bin/mtp-server
	fi

	#restart network for usb0
	if [ $RNDIS_EN = on ];then
		/sbin/ifup usb0
	fi
}

program_kill()
{
	P_PID=`ps | grep $1 | grep -v grep | awk '{print $1}'`
	test -z ${P_PID} || kill -9 ${P_PID}
}

usb_device_stop()
{
	touch /tmp/.udc_pause
	sync
        echo h > /sys/bus/platform/devices/f8102800.usb/udc_ctrl
	echo "" > ${USB_CONFIGFS_DIR}/UDC
	program_kill adbd
	program_kill mtp-server
	ls ${USB_CONFIGS_DIR} | grep f[0-9] | xargs -I {} rm ${USB_CONFIGS_DIR}/{}
	#rm /tmp/.udc_pause
	sync
}

common_start()
{
	export OMX_BELLAGIO_REGISTRY=/root/.omxregister
	omxregister-bellagio /usr/lib/bellagio
}

uvc_start(){
	UVC_CONFIG_FILE=/etc/.usb_config
	UVC_LOG_PATH=/var/log/uvc
	UVC_LOG_FILE=/var/log/uvc/gst-source.log

	if [ ! -d ${UVC_LOG_PATH} ]; then
		mkdir  -p  ${UVC_LOG_PATH}
	fi

	# check uvc
	if [ ! -f ${UVC_CONFIG_FILE} ]; then
		echo "[`date +'%F %T'`] no ${UVC_CONFIG_FILE} file" >> ${UVC_LOG_FILE}
		exit 0
	fi

	cat ${UVC_CONFIG_FILE} | grep -q _uvc
	if [ $? -ne 0 ]; then
		echo "[`date +'%F %T'`] file ${UVC_CONFIG_FILE} no open uvc" >> ${UVC_LOG_FILE}
		exit 0
	fi

	DEVICE_VIDEO_0=/dev/video0
	DEVICE_VIDEO_1=/dev/video1

	device_videos=`v4l2-ctl --list-devices 2>/dev/null | grep -A2 gadget | grep -v gadget | grep -v grep`
	if [ -n "${device_videos}" ]; then
		DEVICE_VIDEO_0=`echo ${device_videos} | awk '{print $1}'`
		DEVICE_VIDEO_1=`echo ${device_videos} | awk '{print $2}'`
	fi

	echo "uvc device video file: ${DEVICE_VIDEO_0} ${DEVICE_VIDEO_1}"

	if [ -z "${DEVICE_VIDEO_0}" ]; then
		echo "[`date +'%F %T'`] not get uvc device file" >> ${UVC_LOG_FILE}
		exit -1
	fi

	if [ ! -c ${DEVICE_VIDEO_0} ]; then
		echo "[`date +'%F %T'`] no ${DEVICE_VIDEO_0} device file" >> ${UVC_LOG_FILE}
		exit -1
	fi

	nohup uvc-gadget -p /etc/sunplus/uvc/ -u ${DEVICE_VIDEO_0} uvc.gs6 &
	sleep 1

	if [ -z "${DEVICE_VIDEO_1}" ]; then
        	echo "[`date +'%F %T'`] no second uvc device file" >> ${UVC_LOG_FILE}
        	exit 0
	fi

	if [ ! -c ${DEVICE_VIDEO_1} ]; then
        	echo "[`date +'%F %T'`] no ${DEVICE_VIDEO_1} device file" >> ${UVC_LOG_FILE}
        	exit 0
	fi

	nohup uvc-gadget -p /etc/sunplus/uvc/ -u ${DEVICE_VIDEO_1} uvc.gs7 &
}

uvc_stop(){
	ps aux | grep uvc-gadget | grep -v grep | awk '{print $2}' | xargs -i kill -9 {}
	echo "uvc-gadget stop"
}

vision_server_start() {
	nohup 3dvision_server --uvc &
}

vision_server_stop() {
	ps aux | grep 3dvision_server | grep -v grep | awk '{print $2}' | xargs -i kill -9 {}
	echo "3dvision_server stop"
}

usb_device_start()
{
	#DIR=$(cd `dirname $0`; pwd)
        DIR=/etc
        if [ ! -e "$DIR/.usb_config" ]; then
                echo "$0: Cannot find .usb_config"
                exit 0
        fi

        if [ -e /tmp/.usb_config ]; then
                USB_CONFIG_FILE=/tmp/.usb_config
        else
                USB_CONFIG_FILE=$DIR/.usb_config
                cp $DIR/.usb_config /tmp/.usb_config
        fi

        parameter_init
        if [ -z $CONFIG_STRING ]; then
                echo "$0: no function be selected"
                exit 0
        fi
        test -d ${USB_CONFIGFS_DIR} || configfs_init
        use_os_desc
        echo $PID > ${USB_CONFIGFS_DIR}/idProduct
        bind_functions
        pre_run_binary
        UDC="f80a1000.dwc3"
        if [ $GADGET_DEVICE = usb2 ];then
                UDC="f8102800.usb"
                echo host > /sys/kernel/debug/usb/f80a1000.dwc3/mode
        fi
        sleep 1
        echo $UDC > ${USB_CONFIGFS_DIR}/UDC
        run_binary
}

case "$1" in
start)
	#common_start
	usb_device_start
	#vision_server_start
	uvc_start

	if [ $GADGET_DEVICE = usb2 ];then
		sleep 2
                echo d > /sys/bus/platform/devices/f8102800.usb/udc_ctrl
        fi
	;;
stop)
	#vision_server_stop
	uvc_stop
	#usb_device_stop
	;;
restart|reload)
	# Do restart usb by udev
	echo "USB_FORCE_CHANGED" >> /tmp/.usb_config
	usb_device_stop
	sleep 1
	$0 start
	# Don't forget to clear "USB_FORCE_CHANGED"
	sed -i "/USB_FORCE_CHANGED/d" /tmp/.usb_config
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
