#!/bin/bash

start()
{
        nohup /usr/bin/monitor_mem.sh &
}

stop()
{
        ps aux | grep monitor_mem | grep -v grep | awk '{print $2}' | xargs -i kill -9 {}
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        *)
                echo "Usage: $0 {start}" >&2
                exit 1
                ;;
esac

